# Generated by Django 3.2.8 on 2021-10-16 13:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0002_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
