# Generated by Django 3.2.8 on 2021-10-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0005_auto_20211016_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_id',
            field=models.CharField(max_length=50),
        ),
    ]
