# Generated by Django 3.2.8 on 2021-10-16 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0010_auto_20211016_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityTypeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.application')),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.facilitytype')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='facility_types',
            field=models.ManyToManyField(related_name='applications', through='graphql_api.FacilityTypeApplication', to='graphql_api.FacilityType'),
        ),
    ]
