# Generated by Django 3.2.8 on 2021-10-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0012_auto_20211016_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='room_type',
        ),
    ]
