# Generated by Django 3.2.8 on 2021-10-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0013_remove_application_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.application')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.propertytype')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='property_types',
            field=models.ManyToManyField(related_name='applications', through='graphql_api.PropertyTypeApplication', to='graphql_api.PropertyType'),
        ),
    ]
