# Generated by Django 3.2.8 on 2021-10-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0014_add_property_types_ty_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='preferred_cities',
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_cities',
            field=models.ManyToManyField(related_name='applications', through='graphql_api.ApplicationPreferredCity', to='graphql_api.City'),
        ),
    ]
