# Generated by Django 3.2.8 on 2021-10-17 03:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0015_alter_application_preferred_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_applications', to='graphql_api.application')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.recommendation')),
                ('recommended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.recommendationapplication')),
            ],
            options={
                'unique_together': {('recommendation', 'application')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='recommendations',
            field=models.ManyToManyField(related_name='applications', through='graphql_api.RecommendationApplication', to='graphql_api.Recommendation'),
        ),
    ]
