# Generated by Django 3.2.8 on 2021-10-17 04:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0017_make_recommendationapplication_recommended_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
