# Generated by Django 3.2.8 on 2021-10-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0016_make_fields_nonnull'),
        ('graphql_api', '0018_city_coordinates'),
    ]

    operations = [
    ]
