# Generated by Django 3.2.8 on 2021-10-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0019_merge_0016_make_fields_nonnull_0018_city_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recommendationapplication',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_applications', to='graphql_api.recommendation'),
        ),
    ]
