# Generated by Django 3.2.8 on 2021-10-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0020_auto_20211017_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='number_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
